// auth types
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// move types
export const FETCH_MOVES = "FETCH_MOVES";
export const FETCH_MOVES_SUCCESS = "FETCH_MOVES_SUCCESS";
export const FETCH_MOVES_FAILURE = "FETCH_MOVES_FAILURE";
export const FETCH_MOVE_NAMES = "FETCH_MOVE_NAMES";
export const FETCH_MOVE_NAMES_SUCCESS = "FETCH_MOVE_NAMES_SUCCESS";
export const FETCH_MOVE_NAMES_FAILURE = "FETCH_MOVE_NAMES_FAILURE";

// pokemon types
export const FETCH_POKEMON = "FETCH_POKEMON";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_FAILURE = "FETCH_POKEMON_FAILURE";
export const FETCH_POKEMON_NAMES = "FETCH_POKEMON_NAMES";
export const FETCH_POKEMON_NAMES_SUCCESS = "FETCH_POKEMON_NAMES_SUCCESS";
export const FETCH_POKEMON_NAMES_FAILURE = "FETCH_POKEMON_NAMES_FAILURE";

// ability types
export const FETCH_ABILITIES = "FETCH_ABILITIES";
export const FETCH_ABILITIES_SUCCESS = "FETCH_ABILITIES_SUCCESS";
export const FETCH_ABILITIES_FAILURE = "FETCH_ABILITIES_FAILURE";
export const FETCH_ABILITY_NAMES = "FETCH_ABILITY_NAMES";
export const FETCH_ABILITY_NAMES_SUCCESS = "FETCH_ABILITY_NAMES_SUCCESS";
export const FETCH_ABILITY_NAMES_FAILURE = "FETCH_ABILITY_NAMES_FAILURE";

// pokemon type types
export const SET_POKEMON_OFFSET = "SET_POKEMON_OFFSET";
export const SET_POKEMON_SEARCH = "SET_POKEMON_SEARCH";
export const FETCH_TYPES = "FETCH_TYPES";
export const FETCH_TYPES_SUCCESS = "FETCH_TYPES_SUCCESS";
export const FETCH_TYPES_FAILURE = "FETCH_TYPES_FAILURE";
export const FETCH_TYPE_NAMES = "FETCH_TYPE_NAMES";
export const FETCH_TYPE_NAMES_SUCCESS = "FETCH_TYPE_NAMES_SUCCESS";
export const FETCH_TYPE_NAMES_FAILURE = "FETCH_TYPE_NAMES_FAILURE";

// icon types
export const FETCH_ICONS = "FETCH_ICONS";
export const FETCH_ICONS_SUCCESS = "FETCH_ICONS_SUCCESS";
export const FETCH_ICONS_FAILURE = "FETCH_ICONS_FAILURE";



export const FETCH_POSTS = "FETCH_POSTS";
export const NEW_POST = "NEW_POST";

export const FETCH_POKEMONS = "FETCH_POKEMONS";
export const LOADING_POKEMONS = "LOADING_POKEMONS";


export const FETCH_ITEMS = "FETCH_ITEMS";
export const LOADING_ITEMS = "LOADING_ITEMS";

export const FETCH_NATURES = "FETCH_NATURES";
export const LOADING_NATURES = "LOADING_NATURES";

export const FETCH_SETS = "FETCH_SETS";
export const LOADING_SETS = "LOADING_SETS";
export const CACHE_USER_SETS = "CACHE_USER_SETS";
export const NEW_SET = "NEW_SET";
export const EDIT_SET = "EDIT_SET";
export const DELETE_SET = "DELETE_SET";
export const SET_ACTIVE_SET = "SET_ACTIVE_SET";

export const FETCH_TEAMS = "FETCH_TEAMS";
export const LOADING_TEAMS = "LOADING_TEAMS";
export const NEW_TEAM = "NEW_TEAM";
export const EDIT_TEAM = "EDIT_TEAM";
export const DELETE_TEAM = "DELETE_TEAM";
export const SET_ACTIVE_TEAM = "SET_ACTIVE_TEAM";
